### PR TITLE
Feature | Add Timelag to Signatory Data

### PR DESCRIPTION
**Pull request by ThatcherK**
Ticket #1

### CODE REVIEW

**Comment by edwinmp** [comment]
This LGTM, but we cannot merge it in until it's BE dependency is complete.

**Comment by ThatcherK** [comment]
@edwinmp  the backend was already merged and deployed!

**Comment by edwinmp** [comment]
Then I probably don't know how to test this, cos I can't see any data under timeliness for either pages ...

**Comment by ThatcherK** [comment]
I have just checked and it's not there anymore, it was there last Friday, will check with Chris when he returns

**Comment by markbrough** [comment]
It looks like this is in the data under the DI `humportal-data` repository:
https://raw.githubusercontent.com/devinit/humportal-data/gh-pages/signatories.json

However, the front-end is still pointing to `https://brough.io/humportal-data` when it calls the data.

It needs to instead point to the Github Pages version of the `humportal-data` repository. I'm not sure whether that repository is yet set up to serve Github Pages, but possibly not? I can't see the settings tab. I presume it should be then served through `https://devinit.github.io/humportal-data` or something like that?

Once Github Pages is set up for `humportal-data`, you need to adjust this line to set `apiURL` to the correct URL:
https://github.com/devinit/humportal/blob/main/store/index.js#L5

For testing purposes, this seems to work OK for me:
```js
const apiURL = 'https://raw.githubusercontent.com/devinit/humportal-data/gh-pages'
```

**Comment by edwinmp** [comment]
Ah, thanks @markbrough ... was under the impression the existing URL was pulling from `gh-pages` already ... @ThatcherK, could you please make the update [here](https://github.com/devinit/humportal/blob/feature/timelag-display/store/index.js#L5)

**Comment by ThatcherK** [comment]
Updated, please test again @edwinmp

**Comment by markbrough** [comment]
@ThatcherK can we serve `humportal-stats` via Github Pages?

**Review by edwinmp — APPROVED** [review]

**Pull request merged**
